### ISSUE TITLE
Mobile content overlap

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/Libresonic.github.io#15] opened 2017-05-24 02:37 UTC
![screenshot_20170523-213630](https://cloud.githubusercontent.com/assets/1531528/26384584/fabc749c-3fff-11e7-987e-432195357745.png)

**Comment by jooola** [comment] 2017-05-24 02:48
Yeah i know this is a duplicate of #9 .

**Closed** 2017-05-24 17:03 UTC
